config/routes.rb
Rails.application.routes.draw do

  default_url_options( host: ENV.fetch('APP_HOST') )

  resources :queued_users, only: [:new, :create]

  scope 'auth/:confirm_token' do
    resources :queued_users, only: [:show, :update, :edit]
    get  'confirm', to: 'confirm_queue#show',  as: 'confirm_queue'
    post 'resend', to: 'confirm_queue#create', as: 'resend_text'
  end

  resources :admin

  # post "queued_user_create", to: 'queued_users#create'
  # get 'queued_users/new', to: 'queued_users#new'

  # scope 'auth/:id/token/:confirm_token' do
  #   patch '/', to: 'queued_users#update'
  #   get   '/', to: 'queued_users#show', as: 'queued_user'

  #   get  'confirm', to: 'confirm_queue#show',   as: 'confirm_queue'
  #   post 'resend', to: 'confirm_queue#create', as: 'resend_text'
  # end

  root 'queued_users#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/queued_user.rb
class QueuedUser < ApplicationRecord

  validates :name, :number, presence: true
  before_save :strip_number

  def waiting?
    finished_at.blank? && queued_at.present?
  end

  def valid_token?(token)
    token == self.confirm_token
  end

  def strip_number
    # Remove all non numbers: http://rubular.com/r/71Skn8LXOW
    self.number = self.number.gsub(/\D/, '')
  end

  def url_helpers
    Rails.application.routes.url_helpers
  end

  def confirm_url
    url_helpers.confirm_queue_url(id: self.id, confirm_token: self.confirm_token)
  end

  def you_are_next!
    $TwilioClient.messages.create(
      from: ENV['TWILIO_PHONE_NUMBER'],
      to:   self.number,
      body: "You're next! Go line up in person now!"
    )
  end

  def send_confirmation!
    $TwilioClient.messages.create(
      from: ENV['TWILIO_PHONE_NUMBER'],
      to:   self.number,
      body: "Confirm your phone number by visiting #{ confirm_url }"
    )
  rescue Twilio::REST::RequestError => e
    logger.error(e.message)
    self.destroy
    self.errors.add(:number, :not_valid, message: "Number was not valid")
    false
  end

  def self.next_in_line
    where("queued_at is not null"). # they have a confirmed phone number
      where("notified_at is not null"). # have not already been notified
      where(finished: false).       # have not finished
      order(:queued_at)
  end

  def self.waiting_users
    where.not(queued_at: nil). # they have a confirmed phone number
      where(notified_at: nil). # have not already been notified
      where(finished_at: nil). # have not finished
      order(:queued_at)
  end

  def place_in_line
    QueuedUser.waiting_users.where("queued_at < ?", self.queued_at).count
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: ENV.fetch('ADMIN_PASSWORD')

  def index
    @waiting_users  = QueuedUser.waiting_users.paginate(page: params[:page], per_page: params[:per_page] || 30)
    @notified_users = QueuedUser.where.not(notified_at: nil).where(finished_at: nil)
  end

  def create
    user = QueuedUser.waiting_users.first
    user.notified_at = Time.now
    user.save!
    user.you_are_next!
    redirect_back(fallback_location: '/admin')
  end

  def destroy
    user = QueuedUser.find(queued_user_params[:id])
    user.finished_at = Time.now
    user.save!
    redirect_back(fallback_location: '/admin')
  end

  private
    def queued_user_params
      params.permit(:id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  protect_from_forgery with: :exception

  include QueuedUsersHelper
end

app/controllers/confirm_queue_controller.rb
class ConfirmQueueController < ApplicationController

  def show
    @user = QueuedUser.find(queued_user_params[:id])
    if @user.valid_token?(queued_user_params[:confirm_token])
      @user.confirmed = true
      @user.queued_at ||= Time.now
      @user.save!
      redirect_to queued_user_path(@user), notice: "Confirmation success"
    else
      redirect_to queued_user_path(@user), notice: "Confirmation Failed"
    end
  end

  def create
    @user = QueuedUser.find(queued_user_params[:id])
    if @user.valid_token?(queued_user_params[:confirm_token])
      @user.send_confirmation!
      redirect_to queued_user_path(@user), notice: "Confirmation re-sent"
    else
      redirect_to queued_user_path(@user), notice: "Invalid credentials"
    end
  end

  private
    def queued_user_params
      params.permit(:id, :confirm_token)
    end
end

app/controllers/queued_users_controller.rb
class QueuedUsersController < ApplicationController
  before_action :set_queued_user, only: [:show, :edit, :update, :destroy]

  # GET /queued_users
  # GET /queued_users.json
  def index
    @queued_users = QueuedUser.all
  end

  # GET /queued_users/1
  # GET /queued_users/1.json
  def show
  end

  # GET /queued_users/new
  def new
    @queued_user = QueuedUser.new
  end

  # GET /queued_users/1/edit
  def edit
  end

  # POST /queued_users
  # POST /queued_users.json
  def create
    @queued_user = QueuedUser.new(create_user_params)
    @queued_user.confirm_token = SecureRandom.hex

    respond_to do |format|
      if @queued_user.save && @queued_user.send_confirmation!
        format.html { redirect_to queued_user_path(@queued_user), notice: "Confirm your phone number to get in the queue" }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /queued_users/1
  # PATCH/PUT /queued_users/1.json
  def update
    respond_to do |format|
      if @queued_user.update(queued_user_params) && @queued_user.send_confirmation!
        format.html { redirect_to queued_user_path(@queued_user), notice: "Confirm your phone number to get in the queue" }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /queued_users/1
  # DELETE /queued_users/1.json
  def destroy
    @queued_user.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: "You're deleted from the queue" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_queued_user
      @queued_user = QueuedUser.find(find_user_params[:id])
      unless @queued_user.valid_token?(find_user_params[:confirm_token])
        redirect_to '/', notice: "Token not valid"
      end
    end

    def find_user_params
      params.permit(:id, :confirm_token)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_user_params
      params.require(:queued_user).permit(:name, :number)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirm_queue_helper.rb
module ConfirmQueueHelper
end

app/helpers/queued_users_helper.rb
module QueuedUsersHelper
  def queued_user_path(user = nil)
    if user
      super id: user.id, confirm_token: user.confirm_token
    else
      super
    end
  end

  def queued_user_url(user = nil)
    if user
      super id: user.id, confirm_token: user.confirm_token
    else
      super
    end
  end
end

app/views/admin/index.html.erb
<h2>Queue Admin</h2>

<div>
  <h2><%= button_to 'Notify Next in line', admin_index_path, method: :post %></h2>
  <p>
    (Clicking this link sends the next person a text and tells them to come wait in line)
  </p>
</div>

<h3>Notified (<%= @notified_users.count %>)</h3>

<% if @notified_users.blank? %>
  <p>(None, click the "Notify" button above)</p>
<% end %>

<% @notified_users.each.with_index do |user| %>
  <div class="row">
    <div class="one-half column">
      <p><strong><%= user.name %></strong></p>
    </div>
    <div class="one-half column">
      <%= button_to "Finished with #{ user.name }",
            admin_path(id: user.id),
            method: :delete,
            form: {style: 'display:inline-block;'} %>

    </div>
  </div>
  <hr />
<% end %>


<h3>Waiting (<%= @waiting_users.count %>)</h3>


<% if @waiting_users.blank? %>
  <p>(None)</p>
<% end %>

<% @waiting_users.each do |user| %>
  <div class="row">
    <div class="column">
      <p><strong><%= user.name %></strong></p>
    </div>
  </div>
  <hr />
<% end %>

<%= will_paginate @waiting_users %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeepRubyQueued</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/queued_users/_form.html.erb
<%= form_for(queued_user) do |f| %>
  <% if queued_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(queued_user.errors.count, "error") %> prohibited this queued_user from being saved:</h2>

      <ul>
      <% queued_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name (What you want to be called)" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :number, "Phone Number (This is how you get notified)" %>
    <%= f.text_field :number %>
  </div>

  <div class="actions">
    <%= f.submit 'submit' %>
  </div>
<% end %>

app/views/queued_users/edit.html.erb
<h1>Edit your account, you will lose your place in line</h1>

<%= render 'form', queued_user: @queued_user %>

<%= link_to 'Show', @queued_user %> |

app/views/queued_users/index.html.erb
<h1>Queued Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>confirmed</th>
      <th>Confirm token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @queued_users.each do |queued_user| %>
      <tr>
        <td><%= queued_user.name %></td>
        <td><%= queued_user.number %></td>
        <td><%= queued_user.confirmed %></td>
        <td><%= queued_user.confirm_token %></td>
        <td><%= link_to 'Show', queued_user %></td>
        <td><%= link_to 'Edit', edit_queued_user_path(queued_user) %></td>
        <td><%= link_to 'Destroy', queued_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Queued User', new_queued_user_path %>

app/views/queued_users/new.html.erb
<h1>Get in the Queue!</h1>

<p>
  Enter your name and phone number, we'll confirm it, and then send you a text when it's your turn in line.
</p>

<%= form_for(@queued_user) do |f| %>
  <% if @queued_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@queued_user.errors.count, "error") %> prohibited this @queued_user from being saved:</h2>

      <ul>
      <% @queued_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name (What you want to be called)" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :number, "Phone Number (This is how you get notified)" %>
    <%= f.text_field :number %>
  </div>

  <div class="actions">
    <%= f.submit 'submit' %>
  </div>
<% end %>

app/views/queued_users/show.html.erb
<p>
  <h3>
    <%= "You're finished"                                             if @queued_user.finished_at         %>
    <%= "Place in line #{ @queued_user.place_in_line}"                if @queued_user.waiting?            %>
    <%= "Pending phone number confirmation, check your text messages" if @queued_user.queued_at.blank? %>
  </h3>
</p>

<p>
  <strong>Name:</strong>
  <%= @queued_user.name %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @queued_user.number %>
</p>

<%= button_to "Re-send confirmation text", resend_text_path(id: @queued_user.id, confirm_token: @queued_user.confirm_token) %>

<%= link_to 'Edit', edit_queued_user_path(id: @queued_user.id, confirm_token: @queued_user.confirm_token) %>